### PR TITLE
fix: lighten audit log list responses

### LINKED ISSUE #14: Make audit log list responses lightweight
## Summary

The audit log list endpoint currently returns full request and response headers and bodies for every row. Those payload columns can be large, which makes the admin audit table slower and increases database and network work even when users only need summary columns.

## Proposed change

- Keep GET /admin/audit focused on lightweight row summaries.
- Return pagination metadata, including total and has_more.
- Continue serving full request/response payloads from the existing GET /admin/audit/{id} detail route when a row is expanded.

## Validation

- Add coverage that list responses omit payload fields while detail responses still include them.
- Run the standard lint/build checks from CONTRIBUTING where local tooling allows it.

### PR DESCRIPTION
**Pull request by xbattlax**
## Summary

Closes #14.

This keeps the audit log list endpoint focused on lightweight summary rows by omitting request/response headers and bodies from GET /admin/audit. Full payloads remain available through the existing GET /admin/audit/{id} detail route, which the audit table now calls only when a row is expanded.

## Changes

- Add a summary query path for audit log list responses.
- Return total and has_more pagination metadata from GET /admin/audit.
- Cap requested audit list page size to avoid accidental very large responses.
- Lazy-load full audit entry details in the UI when a row expands.
- Add integration coverage that list responses omit payloads while detail responses preserve them.

## Validation

- go test -c -o /tmp/crabtrap-admin.test ./internal/admin
- go test -c -o /tmp/crabtrap-proxy.test ./internal/proxy
- go vet ./...
- /Users/nathanmetzger/go/bin/staticcheck ./...
- make build-web

Note: go test ./internal/admin is blocked locally because Testcontainers cannot find rootless Docker in this environment.

### CODE REVIEW

**Comment by xbattlax** [comment]
Rebased this branch on current main in 5ef0884 and resolved the conflict introduced by the merged streaming PR (#5).

The conflict resolution keeps QuerySummaries for the lightweight audit list work and keeps UpdateResponse on the audit reader test stubs from #5.

Local verification:
- go test -c -o /tmp/crabtrap-admin.test ./internal/admin
- go vet ./...
- /Users/nathanmetzger/go/bin/staticcheck ./...
- make build-web
- git diff --check

CI is running again after the branch update.

File: internal/admin/api.go [hunk 1]
```diff
@@ -320,11 +322,22 @@ func (a *API) handleAuditLog(w http.ResponseWriter, r *http.Request) {
 		}
 	}
 
-	entries := a.reader.Query(filter)
+	total, err := a.reader.Count(r.Context(), filter)
```
Comment (bjhaid) [inline internal/admin/api.go]: count queries are very expensive, we shouldn't use this here, it probably will start to timeout over time. see [this](https://wiki.postgresql.org/wiki/Slow_Counting)

File: internal/admin/api.go [hunk 2]
```diff
@@ -320,11 +322,22 @@ func (a *API) handleAuditLog(w http.ResponseWriter, r *http.Request) {
...
+	}
 	respondJSON(w, http.StatusOK, map[string]interface{}{
-		"entries": entries,
-		"offset":  filter.Offset,
-		"limit":   filter.Limit,
+		"entries":  entries,
+		"total":    total,
+		"offset":   filter.Offset,
+		"limit":    filter.Limit,
+		"has_more": filter.Offset+len(entries) < total,
```
Comment (bjhaid) [inline internal/admin/api.go]: rather than doing this, I'll just always query `limit+1`, removing one from the entries when returning to the UI and this will be len(entries) > limit, avoids slow total query and prevents one postgres

**Review by bjhaid — CHANGES_REQUESTED** [review]
can you also please include a screen recording of this in action? if you are using LLMs you can just tell them to test this and give you a recording via an headless browser, they are usually smart enough to figure that out.

File: internal/admin/api.go (hunk 2 above)
Comment (xbattlax) [reply internal/admin/api.go]: Addressed in 3bcc984.

The handler now queries limit+1, returns at most limit entries, and computes has_more from len(entries) > limit. The frontend now uses has_more directly and displays the loaded count instead of relying on an exact total.

File: internal/admin/api.go (hunk 1 above)
Comment (xbattlax) [reply internal/admin/api.go]: Addressed in 3bcc984.

GET /admin/audit no longer runs Count for list pagination. It now requests one extra summary row with limit+1, trims the extra row before responding, and avoids returning an exact total.

**Comment by xbattlax** [comment]
Addressed the review feedback in 3bcc984 and added the requested screen recording in d497119.

Review ledger:
- Removed the expensive exact count query from GET /admin/audit.
- Switched audit list pagination to limit+1 and compute has_more from the extra row.
- Updated the UI store/hook to use has_more and show the loaded count instead of an exact total.
- Added/updated coverage for payload omission, no total field, and limit+1 pagination.
- Screen recording: https://raw.githubusercontent.com/xbattlax/CrabTrap/fix/lightweight-audit-log-list/docs/assets/pr-15-audit-trail-demo.webm

Local verification:
- go test -c -o /tmp/crabtrap-admin.test ./internal/admin
- go vet ./...
- /Users/nathanmetzger/go/bin/staticcheck ./...
- make build-web
- git diff --check

CI has been re-triggered by the branch update.

**Comment by xbattlax** [comment]
Follow-up after Greptile's latest note: addressed the SSE + pagination duplicate risk in 53d1f72.

Audit entries are now deduplicated when pages are merged into the store, using id when available and request_id + timestamp as the fallback key. That keeps live SSE inserts from being duplicated when a later Load More request returns rows shifted by newer DB entries.

Additional local verification:
- make build-web
- git diff --check

CI has been re-triggered again by the branch update.

**Comment by xbattlax** [comment]
Follow-up after Greptile's latest summary: addressed the JSONB placeholder note in 89fc46c.

The audit summary projection now uses NULL::jsonb for omitted request/response headers instead of '{}'::jsonb, so summary rows do not materialize placeholder header maps. Bodies remain empty strings in list responses, and full payloads still come from GET /admin/audit/{id}.

Additional local verification:
- go test -c -o /tmp/crabtrap-admin.test ./internal/admin
- go vet ./...
- /Users/nathanmetzger/go/bin/staticcheck ./...
- git diff --check

CI has been re-triggered again by the branch update.

**Review by bjhaid — APPROVED** [review]
Thanks!
